apiVersion: v1
kind: Service
metadata:
  name: statistics-service-db
  namespace: boathouse-prod
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    app: statistics-service-db
