apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - image: docker.pkg.github.com/icdps/boat-house/client:latest
        name: client
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always