apiVersion: apps/v1
kind: Deployment
metadata:
  name: management
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: management
  template:
    metadata:
      labels:
        app: management
    spec:
      containers:
      - image: docker.pkg.github.com/icdps/boat-house/management:latest
        name: management
        ports:
        - containerPort: 4000
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always