apiVersion: apps/v1
kind: Deployment
metadata:
  name: statistics-service-api-deployment
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: statistics-service-api
  template:
    metadata:
      labels:
        app: statistics-service-api
    spec:
      containers:
      - image: docker.pkg.github.com/icdps/boat-house/statistics_service_api:latest
        name: statistics-service-api
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always