apiVersion: apps/v1
kind: Deployment
metadata:
  name: statistics-service-worker-deployment
  namespace: boathouse-prod
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: statistics-service-worker
  template:
    metadata:
      labels:
        app: statistics-service-worker
    spec:
      containers:
      - image: docker.pkg.github.com/vitaminc0224/boat-house/statistics_service_worker:latest
        name: worker
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
